#!/usr/bin/env python3
"""Validate commit messages against the repository's Conventional Commits rules."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ALLOWED_TYPES = (
    "feat",
    "fix",
    "refactor",
    "docs",
    "test",
    "chore",
    "ci",
    "build",
    "perf",
    "style",
    "revert",
)

HEADER_PATTERN = re.compile(
    r"^(?P<type>" + "|".join(ALLOWED_TYPES) + r")"
    r"(?:\((?P<scope>[a-z0-9][a-z0-9-]*)\))?"
    r"(?P<breaking>!)?: "
    r"(?P<subject>\S.*)$"
)

ALLOWED_AUTOGENERATED_PREFIXES = (
    "Merge ",
    'Revert "',
    "fixup! ",
    "squash! ",
)

TRAILING_PUNCTUATION = (".", "。", "!", "！", "?", "？")
SUBJECT_MAX_LENGTH = 100


def _write_stderr(message: str) -> None:
    sys.stderr.write(f"{message}\n")


def _read_header(message_file: Path) -> str:
    for raw_line in message_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        return line
    return ""


def validate_header(header: str) -> tuple[bool, str]:
    if not header:
        return False, "commit message 不能为空"

    if header.startswith(ALLOWED_AUTOGENERATED_PREFIXES):
        return True, ""

    match = HEADER_PATTERN.fullmatch(header)
    if not match:
        return (
            False,
            "首行必须符合 `<type>(<scope>): <subject>` 或 `<type>: <subject>` 格式",
        )

    subject = match.group("subject").strip()
    if len(subject) > SUBJECT_MAX_LENGTH:
        return False, f"subject 过长，建议不超过 {SUBJECT_MAX_LENGTH} 个字符"

    if subject.endswith(TRAILING_PUNCTUATION):
        return False, "subject 不要以句号、问号或感叹号结尾"

    return True, ""


def main() -> int:
    if len(sys.argv) != 2:
        _write_stderr("usage: validate_commit_msg.py <commit-msg-file>")
        return 2

    message_file = Path(sys.argv[1])
    try:
        header = _read_header(message_file)
    except FileNotFoundError:
        _write_stderr(f"commit message 文件不存在: {message_file}")
        return 2

    valid, error = validate_header(header)
    if valid:
        return 0

    _write_stderr("commit message 校验失败")
    _write_stderr(f"- 原因: {error}")
    _write_stderr("- 允许格式: <type>(<scope>): <subject>")
    _write_stderr("- 允许 type: " + ", ".join(ALLOWED_TYPES))
    _write_stderr("- 示例: feat(finetune): 支持微调任务批量删除")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
